---
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>
  require_chef_omnibus: latest
  image_ref: ubuntu-12.04-x86_64
  flavor_ref: 2

provisioner:
  name: chef_zero
  environments_path: test/integration/default/environments

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: ubuntu-12.04
      openstack_network_name: net-shared-vlan-25
      username: ubuntu
      key_name: <%= ENV['OS_KEY_NAME'] %>
      private_key_path: <%= ENV['OS_KEY_FILE'] || '~/.ssh/id_rsa' %>
      network_ref:
        - 84685c12-ce9b-4056-8dcb-bfa2283e97bf
    run_list:

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[build-essential::default]
      - recipe[fog_cloud::test]
    attributes:
      apt:
        compile_time_update: true
      openstack_username: <%= ENV['OS_USERNAME'] %>
      openstack_api_key:  <%= ENV['OS_PASSWORD'] %>
      openstack_auth_url:  <%= ENV['OS_AUTH_URL'] %>
      openstack_key_name: <%= ENV['OS_KEY_NAME'] %>
      openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
